version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    # dockerfile: .

    environment:
      - POSTGRES_USER=kissyla
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=users
    ports:
      - "5432:5432"    
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
    postgres: